name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Архивируем мод
      run: zip -r Frostbite-mod.zip content sprites mod.hjson README.md
    
    - name: Сохраняем артефакт
      uses: actions/upload-artifact@v4
      with:
        name: Frostbite-mod
        path: Frostbite-mod.zip
